
 
site_name: John Telford - mkdocs


theme:
    
  name: material

  repo_url: https://github.com/JohnTelford/mkdocs
  repo_name: JohnTelford/mkdocs


  features:
    - content.action.view
    - header.autohide
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation:top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.integrate

  palette:

    primary: teal
    accent: indigo
 
# nav tree
nav:
#
  - Home:
    - Iterative Website Development: index.md

  - Technologies:
    - Workstations: workstations.md
    - Material MkDocs: material_mkdocs.md
    - Markdown: markdown.md
    - Version Control System: 
      - VScode: vscode.md
      - GitHub: github.md
      - Git: git.md


  - Development Stack:
    - Dev Stack: dev_stack.md
    - Dev Stack Details: dev_stack_details.md

  - Remediation: defect_remediation_cost.md

  - Teams:
    - Teams Overview: team_overview.md
    - Define Team: team_define.md
    - Design Team: team_design.md
    - Development Team:
      - Website Development: team_develop.md

      - Development Tools: development_tools.md
      - Programming: programming.md
    - Deploy Team: team_deploy.md
    - Maintenance Team: team_maintenance.md

  - Company:
    - Company: company.md
    - Contact: contact.md

  - Etc:
    - Site Ops: site_ops.md
    - Minimum Viable Product: minimum_viable_product.md
    - Defect Remediation Costs​: defect_remediation_cost.md


plugins:
  - git-revision-date-localized:
      type: timeago
  - search:

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.betterem
  - pymdownx.tasklist:
      clickable_checkbox: true

  - attr_list
  - md_in_html

  - toc:
      permalink: 

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

dev_addr: localhost:8000

copyright: Copyright &copy; 2022 - 2023 John Telford

site_url: https://localhost:8000
