
 
site_name: John Telford - mkdocs

theme:
    
  name: material

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.tracking
    - toc.follow
    - header.autohide

  palette:

    primary: teal
    accent: indigo
 
# nav tree
nav:
#
  - Home:
    - Iterative Website Development: index.md

  - Technologies:
    - Workstations: workstations.md
    - Material MkDocs: material_mkdocs.md
    - Markdown: markdown.md
    - Version Control System: 
      - VScode: vscode.md
      - GitHub: github.md

    
  - Development Stack:
    - Site: website_dev_stack.md

    # - Collaborative Development: collaborative.md

    # - Site Config: site_config.md
    # - Development Diagram: website_dev_stack.md
    # - Preview: preview.md

  - Remediation: defect_remediation_cost.md

  - Teams:
    - Teams Overview: team_overview.md
    - Define Team: team_define.md
    - Design Team: team_design.md
    - Development Team:
      - Website Development: team_develop.md
      # - Development Stack:
#        - Dev Stack Details: dev_stack_details.md
      - Development Tools: development_tools.md
      - Programming: programming.md
    - Deploy Team: team_deploy.md
    - Maintenance Team: team_maintenance.md

  - Company:
    - Company: company.md
    - Contact: contact.md

  - Etc:
    - Site Ops: site_ops.md
    - Minimum Viable Product: minimum_viable_product.md
    - Defect Remediation Costs​: defect_remediation_cost.md

  # - Teams:
  #   - Teams Overview: team_overview.md
  #   - Define Team: team_define.md
  #   - Design Team: team_design.md
  #   - Development Team:
  #     - Website Development: team_develop.md
  #     - Development Stack:
  #       - Dev Stack Overview: website_dev_stack.md
  #       - Dev Stack Details: dev_stack_details.md
  #     - Development Tools: development_tools.md
  #     - Programming: programming.md
  #     - Workstations: workstations.md
  #   - Deploy Team: team_deploy.md
  #   - Maintenance Team: team_maintenance.md


  # - Technology:
  #   - Version Control System:
  #     - What is Git and GitHub: https://www.w3schools.com/git/default.asp
  #     - GitHub: https://github.com/
  #     - Git: https://git-scm.com/
  #   - Website Development:
  #     - MkDocs: https://www.mkdocs.org
  #     - Materials for MkDocs: https://squidfunk.github.io/mkdocs-material/
  # - Site Notes: 
  #   - Remediation: remediation.md
  #   - Glossary: glossary.md

  # - Hype:
  #   - Hype Curve: hype_curve.md
  #   - Hype Guesstimates: hype_guesstimates.md

#       - Development Tools:
#         # - developmenttools.md
#         - vscode.md

#       - Programming:  
#         - programming.md

#       - workstations.md
#       - material.md

#   - Company:
#     - About: company.md
#     - Contact: contact.md


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.betterem
  - pymdownx.tasklist:
      clickable_checkbox: true

  - attr_list
  - md_in_html

  - toc:
      permalink: 

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

dev_addr: localhost:8000

copyright: Copyright &copy; 2022 John Telford


site_url: https://localhost:8000
