
 
site_name: John Telford - mkdocs


theme:
    
  name: material

  features:
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation:top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
    - toc.integrate

  palette:

    primary: teal
    accent: indigo
 
# Repository
repo_name: mkdocs
repo_url: https://github.com/JohnTelford/mkdocs.git

# nav tree
nav:
#
  - Home:
    - Iterative Project Development: index.md

  - Version Control System: 
    - Overview: version_control_overview.md
    - VScode: vscode.md
    - GitHub: github.md
    - Git: git.md

  - Technologies:
    - Content Delivery Network: content_delivery_network.md
    - MkDocs: mkdocs.md
    - Markdown: markdown.md
    - Workstations: workstations.md

  - Development Stack:
    - Iterative Development Stack: dev_stack.md

  - Remediation: defect_remediation_cost.md

  - Teams:
    - Teams Overview: team_overview.md
    - Define Team: team_define.md
    - Design Team: team_design.md
    - Development Team:
      - Website Development: team_develop.md
      - Development Tools: development_tools.md
      - Programming: programming.md
    - Deploy Team: team_deploy.md
    - Maintenance Team: team_maintenance.md

  - Company:
    - Company: company.md
    - Contact: contact.md

  - Site Notes:
    - Site Ops: site_ops.md
    - Minimum Viable Product: minimum_viable_product.md
    - Defect Remediation: defect_remediation_cost.md

plugins:
    - search:
    
      # lang: en
    - git-revision-date-localized:
        type: timeago
      
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.betterem
  - pymdownx.tasklist:
      clickable_checkbox: true

  - attr_list
  - md_in_html

  - toc:
      permalink: 

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

dev_addr: localhost:8000

copyright: Copyright &copy; 2022 John Telford
